# Generated by Django 6.0.2 on 2026-03-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="session_points_counter",
            field=models.IntegerField(default=10),
        ),
    ]
