# Generated by Django 6.0.2 on 2026-03-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("allocator", "0002_session_session_points_counter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="session_points_counter",
        ),
    ]
