# Generated by Django 6.0.2 on 2026-03-19 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocator", "0003_remove_session_session_points_counter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Multiplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CardMultiplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="allocator.card"
                    ),
                ),
                (
                    "assigned_mults",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allocator.multiplier",
                    ),
                ),
            ],
        ),
    ]
