# Generated by Django 6.0.2 on 2026-03-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocator", "0004_multiplier_cardmultiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiplier",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
