# Generated by Django 6.0.2 on 2026-03-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocator", "0005_multiplier_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiplier",
            name="is_positive",
            field=models.BooleanField(default=True),
        ),
    ]
